{% set name = "flask-marshmallow" %}
{% set version = "1.3.0" %}
{% set sha256 = "27a35d0ce5dcba161cc5f2f4764afbc2536c93fa439a793250b827835e3f3be6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - flask >=2.2
    - marshmallow >=3.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_marshmallow

about:
  home: https://github.com/marshmallow-code/flask-marshmallow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Flask + marshmallow for beautiful APIs

  description: |
    Flask-Marshmallow is a thin integration layer for Flask (a Python web
    framework) and marshmallow (an object serialization/deserialization
    library) that adds additional features to marshmallow, including URL and
    Hyperlinks fields for HATEOAS-ready APIs. It also (optionally) integrates
    with Flask-SQLAlchemy.
  doc_url: http://flask-marshmallow.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/flask-marshmallow

extra:
  recipe-maintainers:
    - frol
    - mediocretech
